import { IChapterDetails, IComicDetails } from "@types";
import Image from "components/Image";
import { collection, doc, getDoc, onSnapshot, query, where } from "firebase/firestore";
import LayoutHome from "layouts";
import { db } from "libs/firebase-app";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const WatchComicPage = () => {
  const router = useRouter();
  const slug = router.query?.slug as string;
  const id = router.query?.id as string;
  const [chapterDetails, setChapterDetails] = useState<IChapterDetails | null>(null);
  const [comicDetails, setComicDetails] = useState<IComicDetails | null>(null);
  console.log("comicDetails: ", comicDetails);
  useEffect(() => {
    async function fetchDetailsComic() {
      if (!slug) return;
      const colRef = query(collection(db, "comics"), where("slug", "==", slug));
      onSnapshot(colRef, (snapshot) => {
        snapshot.forEach((doc: any) => {
          doc.data() &&
            setComicDetails({
              id: doc.id,
              ...doc.data()
            });
        });
      });
    }
    fetchDetailsComic();
  }, [slug]);
  useEffect(() => {
    async function fetchChapterDetails() {
      if (!id) return;
      const colRef = doc(db, "chapters", id);
      const docData = await getDoc(colRef);
      const data: any = docData.data();
      setChapterDetails(data);
    }
    fetchChapterDetails();
  }, [id]);
  if (!comicDetails || !chapterDetails) return null;
  return (
    <>
      <Head>
        <title>Tổng Tài Tại Thượng - Chap 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <div className="layout-container">
          <div className="text-center">
            <h1 className="pt-5 text-xl font-bold md:text-2xl text-dark4d">
              {comicDetails.title} - {chapterDetails.name}
            </h1>
            <span className="inline-block mt-1">
              [Cập nhật lúc: {new Date(chapterDetails.createdAt.seconds * 1000).toLocaleString()}]
            </span>
          </div>
        </div>
        <section className="py-5">
          {chapterDetails.images.map((image, index) => (
            <Image alt="" src={image} className="mx-auto" key={index} />
          ))}
        </section>
        <div className="layout-container">{/* <CommentItem /> */}</div>
      </LayoutHome>
    </>
  );
};

export default WatchComicPage;
