import Image from "components/Image";
import LayoutHome from "layouts";
import CommentItem from "modules/CommentItem";
import Head from "next/head";

const WatchComicPage = () => {
  return (
    <>
      <Head>
        <title>Tổng Tài Tại Thượng - Chap 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <div className="layout-container">
          <div className="text-center">
            <h1 className="pt-5 text-xl font-bold md:text-2xl text-dark4d">
              Tổng Tài Tại Thượng - Chapter 12
            </h1>
            <span className="inline-block mt-1">[Cập nhật lúc: 20:41 27/12/2022]</span>
          </div>
        </div>
        <section className="py-5">
          {Array(10)
            .fill(0)
            .map((item, index) => (
              <Image
                src="https://comic24h.net/photo.comic24h.net/bloodtear/stories/co-vo-ngot-ngao-co-chut-bat-luong/chap-355/2_03_63ab223f784d6.jpg"
                alt=""
                className="mx-auto"
                key={index}
              />
            ))}
        </section>
        <div className="layout-container">
          <CommentItem />
        </div>
      </LayoutHome>
    </>
  );
};

export default WatchComicPage;
