import { IconHeart, IconShare } from "components/Icons";
import { Image } from "components/image";
import { WrapLink } from "components/link";
import { LayoutHome } from "layouts";
import Head from "next/head";
import React from "react";

const ComicDetailsPage = () => {
  return (
    <>
      <Head>
        <title>Tổng Tài Tại Thượng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <div className="layout-container">
          <section className="flex gap-10 pt-10">
            <WrapLink className="bg-[#999999] rounded overflow-hidden shrink-0">
              <Image
                src="https://cn-e-pic.mangatoon.mobi/cartoon-posters/7859c5a.webp"
                alt=""
                className="aspect-[260/345] w-[260px]"
              />
            </WrapLink>
            <div>
              <h1 className="inline-block text-2xl font-bold text-dark33">Tổng Tài Tại Thượng</h1>
              <span className="inline-block mt-1 text-sm line-clamp-1 text-gray88">
                Tình yêu / Tổng tài / Ngược / Công sở / Mối tình đầu / Đô thị / Bá đạo / Có em bé /
                Gái ngoan
              </span>
              <div className="flex items-center gap-2 mt-3">
                <div className="flex items-center text-[#FFBD4F]">
                  {Array(5)
                    .fill(0)
                    .map((item, index) => (
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        className="w-5 h-5"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                        key={index}
                      >
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                      </svg>
                    ))}
                </div>
                <span className="font-medium text-gray88">4.5</span>
              </div>
              <p className="pt-3 text-sm text-gray88 md:text-base">
                Cung Âu, một tên thiếu gia giàu có mắc bệnh hoang tưởng, và Thời Tiểu Niệm, một tác
                giả truyện tranh nghèo rớt mùng tơi và cô đơn đã bị buộc chặt lấy nhau trong một
                tình huống hết sức trớ trêu: Cung Âu nghĩ Thời Tiểu Niệm đã giấu nhẹm đứa con của
                hai người (không hề). Cùng theo dõi xem nam chính sẽ ngược nữ chính theo những cách
                nào, và làm thế nào mà họ yêu nhau...
              </p>
            </div>
          </section>
          <section className="flex items-center gap-5 mt-4">
            <button
              type="button"
              className="h-12 px-5 font-semibold text-white rounded-[100px] bg-redff4"
            >
              Xem từ đầu
            </button>
            <button
              type="button"
              className="flex items-center h-12 gap-[6px] px-5 font-semibold text-redff4 rounded-[100px] border border-redff4"
            >
              <IconHeart />
              <span>Theo dõi</span>
            </button>
            <button
              type="button"
              className="flex items-center h-12 gap-[6px] px-5 font-semibold text-redff4 rounded-[100px] border border-redff4"
            >
              <IconShare />
              <span>Chia sẻ</span>
            </button>
          </section>
        </div>
      </LayoutHome>
    </>
  );
};

export default ComicDetailsPage;
