import { LayoutHome } from "layouts";
import { HomeBanner, HomeNewest } from "modules/home";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <HomeBanner></HomeBanner>
        <HomeNewest></HomeNewest>
      </LayoutHome>
    </>
  );
};

export default Home;
