import { LayoutHome } from "layouts";
import HomeCategory from "modules/HomeCategory";
import HomeFeatured from "modules/HomeFeatured";
import HomeHot from "modules/HomeHot";
import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Trang chủ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutHome>
        <HomeFeatured />
        <HomeHot />
        <HomeCategory />
      </LayoutHome>
    </>
  );
};

export default HomePage;
